### PR TITLE
treat sys absences in dw prior

### PR DESCRIPTION
**Pull request by kmdalton**
This improves the handling of systematic absences for the double-Wilson prior.

### CODE REVIEW

**Comment by DHekstra** [comment]
I can test this next week with the THz data.

**Comment by kmdalton** [comment]
@DHekstra, can i merged this PR?

**Comment by DHekstra** [comment]
started testing, will let you know asap

**Comment by kmdalton** [comment]
@DHekstra, is it okay to merge this?

**Comment by DHekstra** [comment]
OK, this seems to work as intended. I reran analysis of the (e35) PDZ2 data with results highly similar to before.

**Pull request merged**
